OpenVisualCloud/SVT-HEVC

README.md
Source/App/EbAppConfig.c
Source/App/EbAppMain.c

For linux OS, add support to read from pipe.
Sample app expects FrameToBeEncoded(-n) to be set.

Support reading from pipe

---

Source/App/EbAppConfig.c

Check spelling of parameters start with "-".
Terminate execution with unrecognized parameters.

Terminate sample app with unrecognized parameters

---

Source/API/EbErrorCodes.h
Source/App/EbAppProcessCmd.c
Source/Lib/System/EbInitialRateControlProcess.c
Source/Lib/System/EbPictureControlSet.h

- Fixed crash due to hlRateControlHistorgramQueue overflow
- Fixed UpdateHistogramQueueEntry() function locking on the wrong mutex

VBR Crash Fix

---

CMakeLists.txt
Source/App/CMakeLists.txt
Source/SimpleApp/CMakeLists.txt
libsvt.pc.in

Add pkg-config file support and support make install like normal
build/install with CMake style. After this check, we don't need
to exec the manual install like ffmpeg_plugin.

Build: Update cmake file to support normal build/install in Linux

---

Source/Lib/ASM_AVX2/EbComputeSAD_SadLoopKernel_AVX512.c

GCC generates the aligned loads when derefencing the pointer which can cause segfault.
The workaround is to use unaligned load intrinsic instead of *(*m128).

Fix Debug build segfault on Ubuntu

---

ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
ffmpeg_plugin/0002-doc-Add-libsvt_hevc-encoder-docs.patch
ffmpeg_plugin/README.txt

V2: - Change the config options (didn't need to enable-gpl for BSD+Patent,
it's can compatible with LGPL2+, thanks Xavier correct this part),
now just need to "--enable-libsvthevc" option
- Add force_idr option
- Remove default GoP size setting in the wrapper, SVT-HEVC will calc
the the GoP size internal
- Refine the code as the FFmpeg community's comments
(https://patchwork.ffmpeg.org/patch/11347/)
V1: - base on patch by Huang, Zhengxu, then refine some code.

FFmpeg plugin: Update the FFmpeg plugin patchset

---

Source/Lib/Codec/CMakeLists.txt
Source/Lib/pkg-config.pc.in

The lib include path was incorrect on Windows since 85ecb0d4870430dcd268238c0bc4262cbe724a88
This change fixes it.

set absolute path to libdir in pkg-config config

---

Source/Lib/Codec/EbCodingLoop.c
Source/Lib/Codec/EbPictureDecisionProcess.c

- Sharpness is enabled for content with resolution lower than 4k

Enable sharpness for sub 4k

---

.travis.yml
CMakeLists.txt
README.md

Both [Travis CI](https://github.com/marketplace/travis-ci) & [Coveralls](https://github.com/marketplace/coveralls) need to be enabled on the GitHub Marketplace.

Add continuous integration with Travis & Coveralls

---

Source/Lib/Codec/EbEntropyCoding.c

It's caused by vps_timing_info_present_flag. vps timing info should be
written to bitstream only if this _present flag is set to 1

Fix conformance error for rbsp_stop_one_bit

---

Source/Lib/Codec/EbEncHandle.c

The code for managing thread affinity isn't portable. While DragonFly and FreeBSD support similar API to Linux their `/proc` implementation doesn't expose CPU topology. Let's restore pre-#46 behavior.

Use all cores if /proc is not mounted

---

Source/App/EbAppMain.c

Copied from
https://github.com/OpenVisualCloud/SVT-VP9/blob/e92a57c099c3accd68bbfba560d7f2aebc450acd/Source/App/EbAppMain.c#L61-L62
https://github.com/OpenVisualCloud/SVT-AV1/blob/df11eb05714700c84c77bc5958371719f9748821/Source/App/EbAppMain.c#L61-L62
Ctrl+C once stops encoding, Ctrl+C twice aborts immediately. This fixes the second case.
```
$ SvtHevcEncApp -encMode 0 -q 26 -i foo.yuv -w 1280 -h 720 -fps 24 -b foo.ivf
-------------------------------------------
SVT-HEVC Encoder
SVT [version]:  SVT-HEVC Encoder Lib v1.3.0
SVT [build]  :  GCC 4.2.1        64 bit
LIB Build date: Feb 24 2019 06:19:28
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 53
-------------------------------------------
SVT [config]: Main10 Profile    Tier (auto) …
```

Abort encoding after pressing ^C twice on TTY

---

ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

SVT AV1 has changed the duplicated header file names, so I am reverting the change in SVT HEVC.

FFmpeg-Plugin: Revert the header file names' change

---

Source/Lib/Codec/EbAvcStyleMcp.c
Source/Lib/Codec/EbCodingLoop.c
Source/Lib/Codec/EbDeblockingFilter.c
Source/Lib/Codec/EbEncDecProcess.c
Source/Lib/Codec/EbEntropyCoding.c
Source/Lib/Codec/EbFullLoop.c
Source/Lib/Codec/EbIntraPrediction.c
Source/Lib/Codec/EbMcp.c
Source/Lib/Codec/EbModeDecision.c
Source/Lib/Codec/EbMotionEstimation.c
Source/Lib/Codec/EbMotionEstimationProcess.c
Source/Lib/Codec/EbPictureAnalysisProcess.c
Source/Lib/Codec/EbPictureOperators.c
Source/Lib/Codec/EbProductCodingLoop.c
Source/Lib/Codec/EbSampleAdaptiveOffsetGenerationDecision.c
Source/Lib/Codec/EbTransforms.c

(1) Remove duplicate definition of `DECODED_PICTURE_HASH`.
- Firstly defined in `Lib/Codec/EbDefinitions.h` line 815.
(2) to (4) Optimize function pointers to utilize `!!(x)` instead of `x && 1`.

Optimize function pointers and duplicate definition of DECODED_PICTURE_HASH

---

Build/windows/generate_vs17.bat

CMake's default "C:\Program Files" location breaks pkg-config and tools using it because there is a space in it.

install Windows version to C:\svt-hevc by default

---

Config/Sample.cfg
Docs/svt-hevc_encoder_user_guide.md
Source/App/EbAppConfig.c

Update the formating on the Sample config file for it to have a more uniform look. Added the EncoderColorFormat variable, it's option and definition needs to be checked. Reformatted the AppConfig file to match the structure of the sample config file to allow easy check if something is missing in the config file or a flag is missing in the documentation. Renamed the LogicalProcessorNumbers to LogicalProcessors in the documentation to match the actual variable name.

Formatting rework and renaming

---

Source/Lib/Codec/EbEncHandle.c

Will print out the same thing if using gcc. Will print out the gcc compatible version plus extra information for clang.
`GCC 8.3.0` for gcc
`GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)`
`GCC 4.2.1 Compatible Clang 7.0.1 (tags/RELEASE_701/final)` for clang

EbEncHandle: Use __VERSION__ macro to print compiler info

---

Source/Lib/Codec/EbIntraPrediction.c

The variable `chromaMode` here is set to the entropy coding value as `EB_U32 chromaMode = (EB_U32)funcIndex`, however it would be utilized in later function call (line: 5625 in this file) for intra prediction.
So, here we should set `chromaMode` as the real prediction mode.

Fix chroma prediction error in function `IntraPredictionOl()`.

---

Source/App/EbAppConfig.c
Source/App/EbAppContext.c
ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

When upstreaming the ffmpeg plugin, a reviewer asked us to change the default profile from Main10 to Main for 8 bits depth, for better compatibility when decoding the coded bitstream. I think the request makes sense, hence this PR.

Set the default profile from Main 10 to Main for better compatibility.

---

ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

Switched to encode2 API from send_frame/receive_packet API, for the latter has FPS being unstable per second issue. Also refined the code lines.
This patch has passed full cycle validation.

FFmpeg-Plugin: Switch to encode2 API and refine code

---

Source/Lib/Codec/EbEncHandle.c

This patch realizeed using `EB_MEMCPY` to copy static configuration parameters to the encoder handler. It can avoid bugs caused by missing parameter assignment, and it also makes the code simpler.

Using MEMCPY to copy configurations in function `CopyApiFromApp()`.

---

Docs/svt-hevc_encoder_user_guide.md
Source/App/CMakeLists.txt
Source/App/EbAppConfig.c
Source/App/EbAppConfig.h
Source/App/EbAppInputy4m.c
Source/App/EbAppInputy4m.h
Source/App/EbAppProcessCmd.c
ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

Migrated changes to support y4m container from SVT-AV1 to SVT-HEVC.  Tested with  
akiyo_cif.y4m from xiph.

y4m container support in SVT-HEVC

---

Config/Sample.cfg
Docs/svt-hevc_encoder_user_guide.md
Source/App/EbAppConfig.c
Source/Lib/Codec/EbEncHandle.c

This change was result of investigating https://github.com/OpenVisualCloud/SVT-HEVC/issues/218 where ffprobe did not report the correct frame rate.  The solution was to use the fpsInVps command line option.  However a better solution is to change the default so that the fps is always written to the Vps structure (unless the user decides to set fpsInVps to false with a parameter).

Changing default value for fpsInVps to TRUE

---

Source/Lib/ASM_AVX2/EbComputeSAD_AVX2.h
Source/Lib/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
Source/Lib/ASM_AVX2/EbComputeSAD_SadLoopKernel_AVX512.c
Source/Lib/ASM_SSE4_1/EbPictureOperators_Intrinsic_SSE4_1.c
Source/Lib/Codec/EbComputeSAD.h

Fix bug in function where subtraction of 8 bit unsigned integers was landing in an 8 bit signed space (not enough bits to store possible answers).  Proposed fix to use zero extend or unpack so that subtraction of 8 bit unsigned integers land in 16 bit space ( leaving enough bits to store possible answers).

SpatialFullDistortionKernel(SSE) fix

---

Source/App/EbAppConfig.c

Maybe svt-hevc could only enable useNaluFile  flag when input nalu file exists.  With throwing a warning instead of an error may be better that we won't stop encoding if we just missing a nalu file : )

Change nalu file setting

---

Source/App/EbAppProcessCmd.c
Source/Lib/Codec/EbEncHandle.c

1) Split EB_STRTOK macro into 2 steps to check for NULL  return (several
Klocwork issues)
2) Added (uint32_t) cast to eliminate compiler warning
3) Decoding buffer size check was failing because of sizeof(decodedString)
check.
Added base64DecodeLength parameter to BaseDecodeFunction call and use that
parameter instead for checking buffer length.

NALU file processing

---

Docs/svt-hevc_encoder_user_guide.md
Source/Lib/Codec/EbDefinitions.h
Source/Lib/Codec/EbEncDecProcess.c
Source/Lib/Codec/EbEncHandle.c
Source/Lib/Codec/EbModeDecision.c
Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
Source/Lib/Codec/EbPictureDecisionProcess.c

- Added M11 to OQ mode (tune1) by applying some M12 SQ (tune 0) features . Adopted features as follow : 
* M12 SQ ME search region .
* M12 SQ chroma level.
* M12 SQ Subpel Parameters .
* M12 SQ Partitioning 
* M12 SQ pf MD parameters.
* M12 SQ ADP level.
* Tune a new level for CU16x16 for better speed / BD-rate tradeoff.
=> M11 tune 1 : Speed = ~189 fps for 4K_60 on 8180 / BD-rate loss compared to M10 Tune1 : ~ 9 % 
- Added the ability to enable/disable BitRateReduction and Sharpness features for tune 1

Added encoder mode11 to tune 1(OQ)

---

Source/Lib/Codec/EbEncHandle.c

Caused by high bitrate, the encoded I frame is larger than 6MB, so
increase the size for now

Fix bug #260

---

Source/API/EbApi.h
Source/App/EbAppConfig.c

1) Invalid characters in `EbApi.h` was fixed;
2) Remove duplicate parameter mapping in `EbAppConfig.c`.

Invalid character in `EbApi.h` and remove duplicate parameter mapping

---

Source/Lib/Codec/EbDefinitions.h
Source/Lib/Codec/EbEncDecProcess.c
Source/Lib/Codec/EbEncHandle.c
Source/Lib/Codec/EbEntropyCodingProcess.c
Source/Lib/Codec/EbInitialRateControlProcess.c
Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
Source/Lib/Codec/EbMotionEstimationProcess.c
Source/Lib/Codec/EbPacketizationProcess.c
Source/Lib/Codec/EbPictureAnalysisProcess.c
Source/Lib/Codec/EbPictureDecisionProcess.c
Source/Lib/Codec/EbPictureManagerProcess.c
Source/Lib/Codec/EbRateControlProcess.c
Source/Lib/Codec/EbResourceCoordinationProcess.c
Source/Lib/Codec/EbSourceBasedOperationsProcess.c
Source/Lib/Codec/EbThreads.c

Shutdown threads in a graceful way

---

appveyor.yml

Temporarily use packages provided from the msys2 project.
Adds on a little bit of time since the vs2019 images still don't msys2 by default
Same pr as https://github.com/OpenVisualCloud/SVT-AV1/pull/490

Appveyor: Use msys2 provided mingw-w64 yasm

---

Source/App/EbAppConfig.c
Source/Lib/Codec/EbEncDecProcess.c
Source/Lib/Codec/EbEncHandle.c

1. Address r2r issue due to the 16x16 and 8x8x data being unavailable to determine the PFMD settings for M11
2. Disable BRR and Improve sharpness by default
Minimal ~1%
Closes #258

Address M11 tune 1 items

---

Source/Lib/Codec/EbRateDistortionCost.c

(1)  The loop-up table `skipFlagBits` was fixed.
In HEVC, there are 3 contexts for `skip_flag` and there are 6 values in the look-up table as follows.
```
static const EB_U32 skipFlagBits[6] = { 17878, 62157, 86651, 54723, 14816, 8254 };
```
This may lead to overflow in bit estimation of skip_flag in function `InterFastCostPsliceOpt()` and `InterFastCostBsliceOpt()`.
```
// Rate
EB_U64 mergeSkiplumaRate;
mergeSkiplumaRate = skipFlagBits[4 + cuPtr->skipFlagContext];
```
(2) some typos in this file was fixed:
- Esimate => Estimate;
- Assigne => Assign;
- decisoion => decision;
- condidate => candidate;

Fix reading overflow of `skipFlagBits[]` and typos in `EbRateDistortionCost.c`.

---

CMakeLists.txt

Don't apply stack protector if mingw since not all mingw-w64 gcc's are compiled with stack-protector included

CMake: apply -fstack-protector-strong if not mingw

---

ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

Closes: #285 
Change typo for YUV422P10.

Fix typo for YUV422P10 since it was missing from the list.

---

Source/Lib/Codec/EbTransforms.c

In RDOQ, the chroma distortion has been scaled twice and the second part is not needed. With this issue fixed, the efficiency in luma component would increase.
Firstly, the chroma distortion was scaled by a weighting factor as follows,
```c++
rdoqError[iteration] = (((rdoqError[iteration] * ChromaWeightFactorRaBase[qp]) + CHROMA_WEIGHT_OFFSET) >> CHROMA_WEIGHT_SHIFT);
```
Secondly, the scaled distortions was scaled again like the `Luma` component as follows.
```c++
rdoqCost[iteration] = ((rdoqError[iteration]) << COST_PRECISION) + (((lambda * rdoqBits[iteration]) + MD_OFFSET) >> MD_SHIFT);
```
However, I think the second scaling process is not needed and should be removed.
For reference, we can found the RDCost derivation in `EbRateDistortionCost.c` as follows,
```c++
// Compute Cost …
```

Fix Rate-Distortion Cost derivation error in RDOQ of chroma component

---

Source/Lib/Codec/EbEncHandle.c

Handle the case when IntraPeriodLength is equal
to -1 by avoiding a EB_U32 cast.
Encoder was crashing once the fps value was set
to -1

Fix bug IntraPeriod = -1

---

Source/App/EbAppInputy4m.c

The scan_type variable is reported as being
"unused but set variable" when compiling in Linux.
Using the #ifdef PRINT_HEADER preprocessor to hide
it from the compiler

scan_type is unused but set

---

gstreamer-plugin/git-patch/0001-svthevcenc-Add-svthevc-encoder-element.patch

* Fix merge conflict in latest Gstreamer
* Fix some issues when building in meson build system 
* Port to codec-utils API for parsing range extension profile
- See https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/merge_requests/23
* Change max supported PROP_ENCODER_MODE property value (https://github.com/OpenVisualCloud/SVT-HEVC/pull/263)
* Mark PROP_TUNE property as deprecated (https://github.com/OpenVisualCloud/SVT-HEVC/pull/263)
And apart from the above, PROP_PRED_STRUCRE property is added.

Gstreamer plugin: Apply changes to git-patch based on the latest Gstreamer and SVT-HEVC

---

Source/Lib/Codec/EbResourceCoordinationProcess.c
Source/Lib/Codec/EbSei.c
Source/Lib/Codec/EbSequenceControlSet.c
Source/Lib/Codec/EbSequenceControlSet.h

1) In function `CopySequenceControlSet()`, paramters were assigned one by one. This would introde bugs if some parameters were not set. I followed the assignements here and copied the beging part started with `staticConfig` and ended with `pictureControlSetPoolInitCount`.
Actually, parameters like `enableStrongIntraSmoothing`, `reduceCodingLoopCandidates`, `maxDpbSize` and other parametres were missing in the former version.
2) In the 2nd commit, `encoderBitDepth` parameter was assigned with the video size and the long expression `contextPtr->sequenceControlSetInstanceArray[instanceIndex]->sequenceControlSetPtr` was replaced by the local variable `sequenceControlSetPtr` .

Optimize Copy of SequenceControlSet and initial value assignment

---

Source/Lib/Codec/EbEntropyCoding.c

I have reported a bug that doesn't end encoding. (https://github.com/OpenVisualCloud/SVT-HEVC/issues/305)
This happens when using the EbH265EncStreamHeader API, after initializing the encoder with codeVpsSpsPps and before receiving the encoded packet.
In this case, some fields such as maxDpbSize, encoderBitDepth in SequenceControlSet that using by PacketizationKernel thread was not copied from main thread. So since the maxDbpSize value is 0 when creating VPS, WriteUvlc does infinite loop.

Fix infinite loop when encoding with codeVpsSpsPps enabled

---

appveyor.yml

closes #332
Right now the debug msvc build is failing as noted in #331
Right now investigating into properly using ccache for mingw-w64 gcc and maybe sccache for both gcc and cl.exe if possible

Appveyor: Add debug and basic encoding tests along with mingw builds

---

Source/Lib/Codec/EbEncHandle.c

This is referencing #181 
There was a socket_id > 15 clause that would cause it to throw an error on any machine with 16 or more sockets. While this would never occur with physical hardware it is possible to occur with virtual machines. Virtual machines can configure their systems to do 1 socket per core or really anything. Here is the lscpu of my configuration that I used to validate. Unfortunately I can only test up to 64 sockets with my little 8 core, anymore than that and the VM does not boot. I tested this via ffmpeg and stopped it after it encoded a about 20 seconds or so and it looks like it is encoding just fine. I would like it if other people validated this with their machines with higher counts if possible, I do not know if it will work if you go passed 128 due to there being …

Remove limitation of less than 16 Sockets

---

Source/Lib/Codec/EbEncHandle.c

(Regression of PR #264 for windows debug build)
This happen in Visual Studio 2017 Debug version.
To be clear: compilation succeeded but encoding fails

Fix issue #331

---

Source/Lib/Codec/EbEncHandle.c

For non-numa architecture, users can use taskset to specify cores

Don't set affinity if not necessary

---

appveyor.yml

Appveyor seems to have finally included msys2 in their 2019 images. Nice.

Appveyor: Fix appveyor builds

---

.travis.yml
appveyor.yml

Add ffmpeg builds to appveyor for testing windows mingw-w64 builds. Orignally had a msvc ffmpeg build, but is excluded since it takes a lot of time and can not easily be speed up

Appveyor: Add ffmpeg build

---

Source/Lib/Codec/EbEncHandle.c
Source/Lib/Codec/EbEntropyCoding.c

The encoderBitDepth field required to generate the H265 range extension profile indicator,
but it was not copied from the API. So for all bit depth encodings were indicated as 8bits in the 
range extension profile.
And the bitstream conforming to the format range extentions profiles should obey
the constraints defined by ITU-T H.265. But current code does not conform to 
the constraints in some cases. Such as, the previous generate a incorrect main-422-10 profile with 
the general_max_8bit_constraint_flag set to 1 when encoding YUV422/8bit with ConstrainedIntra mode.
The latest ITU-T H.265 revision referenced is (02/2018).

Fix wrong bitstream indication for conformance to MainRext

---

appveyor.yml

Instead of trying to push all 5 builds to GitHub on a release, it now only deploys the Release build from Visual Studio 2019.
Aside from that, it seems that the `secure auth_token` is not working, since [AppVeyor did fail](https://ci.appveyor.com/project/OpenVisualCloud/svt-hevc/builds/27345109) on the v1.4.1 tag.
```
Deploying using GitHub provider
Creating "v1.4.1" release for repository "OpenVisualCloud/SVT-HEVC" tag "v1.4.1" commit "02fd1261966acfae6b363d8213710ef7505f0f31"...Error creating GitHub release: Provider setting not found or it's value is empty. If secure setting is used please check that value was encrypted (or YAML was exported) while being logged under correct account.
Parameter name: auth_token
```
I think it wasn't changed (correctly) when #92 got merged. @hassount or …

Update AppVeyor to only deploy VS19 Release build to GitHub Releases

---

Source/Lib/Codec/EbTransforms.c

The issue can be reproduced in legacy CPUs without AVX intrinsic, or
by hard coding ASM_TYPES with 1. It's caused by some incorrect
implementation of Transform8x8_SSE4_1_INTRIN() for 10-bit YUV source.
(Need to check whether the issue also happens or not with 8-bit YUV
source.)
So temporarily worked around this issue, like what the function
transformFunctionTableEncode1() is invoked since v1.2.0. And did the
same change for N2 and N4 transform coefficient shapes in addition to
the default one, just in case.
Resolved #[259](https://github.com/OpenVisualCloud/SVT-HEVC/issues/259).

Worked around the incorrect tranform issue with AVX unsupported CPU.

---

Source/Lib/Codec/EbDefinitions.h
Source/Lib/Codec/EbEncHandle.c

By checking whether the processor supports XGETBV instruction or not,
beforeing invoking it to check ZMM/YMM/XMM states are enabled in XCR0
register.
Partially fixed the encoding process crash issue #274 .

Fixed the encoding crashing issue for some legacy CPUs.

---

Source/App/EbAppConfig.c

Adjusted the logic in  SetCfgInputFile to call check_if_y4m if the
inputFile is stdin
Fixes y4m portion of https://github.com/OpenVisualCloud/SVT-HEVC/issues/373

Fix y4m check with stdin

---

Source/App/EbAppConfig.c
Source/App/EbAppConfig.h
Source/App/EbAppInputy4m.c
Source/App/EbAppInputy4m.h
Source/App/EbAppProcessCmd.c

The issue was caused by the definition of EB_STRNCPY invoking strncpy_ss
with sizeof(dst). sizeof() an array can return the memory size of the
array, while sizeof a pointer pointing to an array would return the size
of the pointer (8 in 64bit machine, and 4 in 32bit one). So that dmax of
strncpy_ss was always 8 or 4, and would cause the byte assignment issue
once the size of source was greater or equal than dmax.

Fixed the Y4M header analysis issue in SvtHevcEncApp.

---

gstreamer-plugin/CMakeLists.txt

Fixed a missing dependency in CMakeLists.txt resulting in linking errors on some systems.

gstreamer plugin missing dependency fix in CMakeLists.txt

---

Source/Lib/Codec/EbModeDecisionConfigurationProcess.c

The `cu8x8Index` here is wrong for `lcuParams->rasterScanCuValidity[cu8x8Index]` check.

Fix 8x8 CU scan index error in function `DeriveLcuScore()`.

---

Source/Lib/Codec/EbPictureAnalysisProcess.h
Source/Lib/Codec/EbSourceBasedOperationsProcess.h

Resolve the following errors:
```
In file included from D:\Downloads\SVT-HEVC\Source\Lib\Codec\EbEncHandle.c:30:
In file included from D:\Downloads\SVT-HEVC\Source\Lib\Codec/EbPictureAnalysisProcess.h:11:
D:\Downloads\SVT-HEVC\Source\Lib\ASM_AVX2\EbNoiseExtractAVX2.h(56,2): error : unknown type name '__m256i'
In file included from D:\Downloads\SVT-HEVC\Source\Lib\Codec\EbEncHandle.c:34:
In file included from D:\Downloads\SVT-HEVC\Source\Lib\Codec/EbSourceBasedOperationsProcess.h:11:
D:\Downloads\SVT-HEVC\Source\Lib\ASM_AVX2\EbNoiseExtractAVX2.h(56,2): error : unknown type name '__m256i'
```

Fix compilation error on clang-cl

---

Source/Lib/Codec/EbProductCodingLoop.c

In function `LinkBdptoMd()` and `LinkMdtoBdp()`, when one CU is coded in `Intra2Nx2N` mode, the `predictionModeFlag` was passed as `intraLumaMode` to update the neighboring information arrays.
This commit fixed the above error.

Fix LumaIntraMode storage error in function `LinkBdptoMd()` and `LinkMdtoBdp()`

---

Source/App/EbAppConfig.c

Adding a configuration check that the compressed 10 bit format can only
be used if the encoder bit depth is also 10 bits.

10bit compressed check

---

Source/Lib/Codec/EbMdRateEstimation.c

In 10bit coding, the offset value can be larger than 7. The range is defined as follows in file `EbSampleAdaptiveOffsetGenerationDecisioin.c`.
```
static EB_S32 MinSaoOffsetvalueEO[2 /*8bit+10bit*/][SAO_EO_CATEGORIES] = { {0, 0, -7, -7},{0,  0, -31, -31} };
static EB_S32 MaxSaoOffsetvalueEO[2 /*8bit+10bit*/][SAO_EO_CATEGORIES] = { {7, 7,  0,  0},{31, 31, 0,    0} };
static EB_S32 MaxSaoOffsetvalueBO[2 /*8bit+10bit*/] = { 7 , 31 };
static EB_S32 MinSaoOffsetvalueBO[2 /*8bit+10bit*/] = { -7 ,-31 };
```
When the offset value is larger than the array size of `saoOffsetTrunUnaryBits`, reading overflow would happen.
This commit forces a maxminum value of 7.

Fix reading overflow when estimating bits for SAO offset values in 10bit

---

Source/Lib/Codec/EbEncHandle.c

There's a comment in [gstsvthevcenc.c](https://github.com/OpenVisualCloud/SVT-HEVC/blob/1ec6f6d6b9fbbd4f0a2d1e36a493dba12d7dfbae/gstreamer-plugin/gstsvthevcenc.c#L993-L997) that should be checked with this fix (I didn't test GStreamer):
```c
/* if pAppPrivate is indeed propagated, get the frame through it
* it's not currently the case with SVT-HEVC 1.3.0
* so we fallback on using its PTS to find it back */
if (output_buf->pAppPrivate) {
frame = (GstVideoCodecFrame *) output_buf->pAppPrivate;
} else {
```

Fix pAppPrivate not propagating to the output.

---

Source/Lib/Codec/EbPacketizationProcess.c

Set fillerBytes to 0 if it would wrap-around to max uint32. This will end up sending FILLER_DATA_OVERHEAD(6) bytes as filler still with no ff_bytes (which is valid).

Fix integer wrap-around in fillerBytes for CBR VBV.

---

Source/Lib/Codec/EbEncHandle.c

Otherwise will cause failure in app which uses library directly, e.g. gst plugin.

Add missing vbv initial value in library

---

gstreamer-plugin/gstsvthevcenc.c

pAppPrivate is propagated to output now.
But the logic is kept unchanged in gst for backward compatibility.

GStreamer plugin: update pAppPrivate related comments

---

Source/App/EbAppConfig.c
Source/App/EbAppProcessCmd.c
Source/Lib/Codec/EbCodingLoop.c
Source/Lib/Codec/EbEncHandle.c

Adding support for:
10bit YUV422 2bit compressed
1) Adjusted the frame size in the
sample encoder app (ProcessInputBuffer)
2) Adjusted the size of the incremental Cb and Cr buffers in
EbEncHandle.c/AllocateFrameBuffer()
3) Adjusted the offsets and widths in EbCodingLoop.s/EncodePassPackLcu()
Verified using:
ParkJoy_864x480_10bit_50Hz_P422.yuv
and checked for regressions using:
Netflix_Crosswalk_3840x2160_10bit_60Hz_P420.yuv
Changes also made to YUVTools to support chroma modes other than YUV422.

10bit YUV422 2bit compressed

---

Source/Lib/Codec/EbPictureDecisionProcess.c
Source/Lib/Codec/EbResourceCoordinationProcess.c

When the application send fake frames (such as with EOS flag), the
encoder should make each frame go through the whole encoding kernel
stages (from ResourceCoordination to Packetization), otherwise
EbH265GetPacket() would be blocked in waiting for the buffer posted
by Packetization.
Fixes #367 .

Fixed the hang issue with each EOS frame.

---

Source/Lib/Codec/EbEncHandle.c

Changed the log for the level value so that the decimal value
(e.g. 6.2 vs 6.0) is correctly shown.  Float cast is now
done on the pre-decimated value rather than the
post-decimated value where the decimal value was
already lost.

Decimal value of level

---

Source/Lib/Codec/EbEncHandle.c

(When receiving only 1 frame input, )SvtHevcEncApp or any application
may invokes EbDeinitEncoder() ahead of all the kernel threads complete
processing. And EbDeinitEncoder() would free all the recorded memory
objects which may be still used by some threads, so that race condition
happens.
So fixed (worked around) this issue by terminating the kernel threads
before freeing memories. Ideally, there should be some object reference
and unreference mechanism to make the objects access safe.
Note:
1. EbObjectIncLiveCount() couldn't be helpful to address such race
condition, because it just avoids that an EbObjectWrapper_t object
wouldn't be returned back to an empty queue prematurely;
2. EB_SEND_END_OBJ() plus EB_CHECK_END_OBJ() (induced in PR #270) could
not avoid such race condition, either. …

Fixed the core dump issue with only 1 frame input.

---

Source/Lib/Codec/EbSequenceControlSet.c
Source/Lib/Codec/EbSequenceControlSet.h

Because the lcuParamsArray of an SCS object will be allocated through
ResourceCoordinationKernel()->LcuParamsInit() later. With it removed,
about 4.5MB memory ((EB_SequenceControlSetPoolInitCount + 1) *
sizeof(LcuParams_t) * 146 * 80) can be saved.
Fixes #416 .

Removed the redundant LcuParamsCtor() calling.

---

Source/Lib/Codec/EbPictureDecisionProcess.c

The regression was caused by PR #250. So fixed it by rolling back to
the original logic to set IDR (and CRA) flag.
Fixes #423 .

Fixed the IDR insertion failure regression.

---

ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

Adding high dynamic range (-hdr) option to SVT-HEVC ffmpeg plugin
Fixes #430

FFmpeg-Plugin: add high dynamic range

---

Config/SVTSegmentOvFile.txt
Config/Sample.cfg
Docs/svt-hevc_encoder_user_guide.md
Source/API/EbApi.h
Source/App/EbAppConfig.c
Source/App/EbAppConfig.h
Source/App/EbAppContext.c
Source/App/EbAppProcessCmd.c
Source/Lib/Codec/EbCodingLoop.c
Source/Lib/Codec/EbEncDecProcess.c
Source/Lib/Codec/EbEncHandle.c
Source/Lib/Codec/EbEntropyCoding.c
Source/Lib/Codec/EbModeDecisionProcess.c
Source/Lib/Codec/EbPictureControlSet.c
Source/Lib/Codec/EbPictureControlSet.h
Source/Lib/Codec/EbPictureManagerProcess.c
Source/Lib/Codec/EbResourceCoordinationProcess.c

Hi, I want to introduce new feature for HEVC
The point is to give users ability to change QP and densilty for each LCU and image separately.
This feature is rather for very specific use-case like surveillance systems, where objects like pedestrians or vehicles are detected and tracked (encoded with higher quality) while background is encoded with worse quality. Thanks to encoding only key areas with good quality bitstream is smaller and still have high value
I added new parameter "-segment-ov-file" which read qp values from file and send it to encoder (as example)
I am open to any suggestions.

Enabling segment override for each LCU separatelly

---

Source/App/EbAppInputy4m.c
Source/App/EbAppProcessCmd.c

Reverts OpenVisualCloud/SVT-HEVC#436 which breaks reading 10bits and -nb input.
For non-stdin input(-i), only seekable stream is supported by sample app for now.
For other corner case(fifo, socket etc.) please disable y4m probing(in SetCfgInputFile) on your personal branch.
Fixes #443  #441

Revert "Fix reading input for fifo in ReadInputFrames"

---

Source/Lib/Codec/EbEncHandle.c

`-interlaced-video 1` has not been updating the VPS and VUI since this line was removed in https://github.com/OpenVisualCloud/SVT-HEVC/commit/5ebc0b284557959a0579dccfc4e5cdee621e06ed#diff-c34b031bdf161695d0bd85bdc4ebf7e3L2052
Confirm using `SvtHevcEncApp -i /dev/zero -b out.265 -interlaced-video 1 -w 1920 -h 540 -fps 60 -n 5`; expect `general_interlaced_source_flag = 1` in the VPS.
Signed-off-by: Don Pham <dpham@live.ca>

Fix interlacedVideo configuration

---

Source/Lib/Codec/EbEncHandle.c

Changed warning message about vtune depreciation:
SVT [WARNING]: -tune is deprecated and will be ignored.

Improve tune warning

---

Source/Lib/Codec/EbEntropyCoding.c

Changed the algorithm used to set the MaxNumReorderPics
written to the bitstream (both in SPS and VPS structures)
NumReorderPics indicates the maximum number of pictures that can precede
any picture in decoding order and follow it in output order.  The value
needs to be no greater than the DPB size
Added DetermineNumReorderPics to calculate the value based on the
prediction structure in the configuration.  For Low Delay we set
NumReorderPics to 0 and for Random Acces we set NumReorderPics to
a value according to the number of hierarchical levels

Optimize MaxNumReorderPics in vps/sps

---

Build/linux/build.sh

Changing the order that cc compilers are
checking in the linux build script.
The Intel C Compiler (icc) is now checked
after gcc and clang so that it only used
when both gcc and clang are not available.

Change icc compiler ordering

---

Source/Lib/Codec/EbPacketizationProcess.c

The first AUD is inserted here:
```c
if (sequenceControlSetPtr->staticConfig.codeVpsSpsPps && toInsertHeaders) {
// Reset the bitstream before writing to it
ResetBitstream(
pictureControlSetPtr->bitstreamPtr->outputBitstreamPtr);
if (sequenceControlSetPtr->staticConfig.accessUnitDelimiter) {
EncodeAUD(
pictureControlSetPtr->bitstreamPtr,
pictureControlSetPtr->sliceType,
pictureControlSetPtr->temporalId);
}
```
So the second AUD now checks if the first one was not inserted.

Fix condition to prevent encoding two AUD in one IDR frame.

---

Source/App/EbAppInputy4m.c

Core problem is that the existing assert and return of
EB_ErrorNone when the y4m frame delimiter is read
are happening when the file stream reader is at the end of
the file.  This can happen when the -n value is larger than the
actual number of frames in the file.
To fix this problem with y4m files, an additional check is
added to when the y4m frame delimiter is being read.  Rather
than asserting after the feof check, the y4m file is rewound, the
header is skipped over, and the frame delimiter is attempted to be
read again.
Note: One alternative solution could be to first figure out how many
bytes are in the file (using fseek and ftell), and then use ftell
to see if the file reader is at the end of the file.
This logic would replace the feof call at the end of ReadInputFrames,
since that …

y4m file rewind logic

---

Source/Lib/Codec/EbDefinitions.h
Source/Lib/Codec/EbEncDecProcess.c
Source/Lib/Codec/EbEntropyCodingProcess.c
Source/Lib/Codec/EbInitialRateControlProcess.c
Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
Source/Lib/Codec/EbMotionEstimationProcess.c
Source/Lib/Codec/EbPacketizationProcess.c
Source/Lib/Codec/EbPictureAnalysisProcess.c
Source/Lib/Codec/EbPictureDecisionProcess.c
Source/Lib/Codec/EbPictureManagerProcess.c
Source/Lib/Codec/EbRateControlProcess.c
Source/Lib/Codec/EbResourceCoordinationProcess.c
Source/Lib/Codec/EbSourceBasedOperationsProcess.c

To track each picture whether it's posted from every encoding kernel or not, after being fed into kernels.
As the message is to track picture level, this change can output picture flow once in each encoding kernel, with redundant outputs eliminated.
The recommended steps to debug encoding dead lock (hang) issue:
1. Track the POCs in the entrance and exit of the encoding pipeline,
by forcibly printing the 1st DEADLOCK_DEBUG log in RC, and the
last DEADLOCK_DEBUG log in PK;
2. Reorder the POC numbers of RC and PK separately, to check the
1st POC which couldn't be outputted from PK;
3. Open the DEADLOCK_DEBUG switch, and change the MIN_POC & MAX_POC
values clamping the range where that POC locates;
2. Check the specific stage where that POC can't go through.
Signed-off-by: Austin Hu …

Refined the DEADLOCK_DEBUG outputs in each encoding stage.

---

Source/Lib/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
Source/Lib/ASM_AVX2/EbComputeSAD_SadLoopKernel_AVX512.c
Source/Lib/C_DEFAULT/EbComputeSAD_C.c

Changed the check for pBestSad64x64 to also
include being equal to the value, as the computed
value might equal pBestSad64x64 without a correct
corresponding motion vector ever being set.
We are thus changing to <= to include this corner
case.
Closes #481

Handle corner case of sad64x64 comparison

---

ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

ffmpeg plugin: expose parameter tile_row_cnt tile_col_cnt and tile_slice_mode

---

Source/Lib/Codec/EbMalloc.c

Increasing MEM_ENTRY_SIZE  x4 to allow for 8k media
encoding using a debug build.
This eliminates seeing these messages when the encoding
is stopped:
SVT: can't add memory entry.
SVT: You have memory leak or you need increase MEM_ENTRY_SIZE
closes #506 

Increase MEM_ENTRY_SIZE

---

Source/Lib/Codec/EbDefinitions.h
Source/Lib/Codec/EbEncHandle.c
Source/Lib/Codec/EbInitialRateControlProcess.c
Source/Lib/Codec/EbPacketizationProcess.c
Source/Lib/Codec/EbSequenceControlSet.h

1. The reason of hang caused by OUT_ALLOC is lack of available output stream buffer.
The fix is to seperate the outputBufferFifoInitCount from inputOutputBufferFifoInitCount.
And increase its size.
2. Remove the OUT_ALLOC macro.
closes #514, #497

Fix hang caused by OUT_ALLOC and remove macro

---

Source/App/EbAppContext.c
Source/App/EbAppContext.h

Since nothing is using the `streamBufferPool`, it would be better to remove it for now
Matching SVT-AV1 PR: https://github.com/OpenVisualCloud/SVT-AV1/pull/1209

App/EbAppContext.c: Remove unused AllocateOutputBuffers

---

Source/Lib/Codec/EbMotionEstimation.c

NxM SAD is calculated between the current LCU buffer and its corresponding
reference one in reconstructed picture for O/A/B/C/D positions.
Note: the same change should be also applied in hme_mv_center_check()
of SVT-AV1.

Update the Y sample buffer indexing for position A in Motion Estimation.

---

Source/Lib/Codec/EbDefinitions.h
Source/Lib/Codec/EbEncHandle.c
Source/Lib/Codec/EbPictureAnalysisProcess.c
Source/Lib/Codec/EbResourceCoordinationProcess.c

Adjusted the PAREF_OUT PR 455
+ Moved the padding of the input picture prior to the copying of the
picture to the picture analysis reference picture
+ Removed the PAREF_OUT #define
Testing has shown this will fix the SVT defield test cases which
were failing because the field dimensions were not a multiple of 8.

Adjust PAREF_OUT

---

Tests/SVT-HEVC_FunctionalTests.py

Changed the logic for the COMPARE variable in run_test back to how it was
originally meant (COMPARE=1 does a comparison).

Test Script COMPARE

---

Source/App/EbAppConfig.c

Fixing an issue reported by running the memory sanitizer on Linux.
Initializing memory allocated for processing the command lines.

Uninitialized memory fix

---

Source/Lib/Codec/EbEncHandle.c

Level 0 is auto level decided by encoder, should not be blocked by level/tier error checking.
Level 0 is auto level decided by encoder, should not be blocked by level/tier error checking.
Fixes #553 
@tianjunwork

Fix -level 0 error checking

---

Source/App/EbAppMain.c

Expand the precision to mitigate overflow in bitrate log print.
@tianjunwork

Expand the precision of bitrate in log print

---

Source/App/EbAppProcessCmd.c
Source/Lib/Codec/EbEncHandle.c

Signed-off-by: Jun Tian <tianjun1.0@gmail.com>
Address the rest static analysis warnings:
Unvalidated integer value '...?y1:y2' that is received from 'fscanf' at line 987 is used as an operand to a binary operator at line 999.
Unvalidated integer value '((x1) > (x2) ? (x1) : (x2)) + 64' that is received from 'fscanf' at line 987 is used as an operand to a binary operator at line 996. Also there is one similar error on line 996.
Unvalidated integer value '...?x1:x2' that is received from 'fscanf' at line 987 is used as an operand to a binary operator at line 996. Also there is one similar error on line 996.
Unvalidated integer value '((y1) > (y2) ? (y1) : (y2)) + 64' that is received from 'fscanf' at line 987 is used as an operand to a binary operator at line 999. Also there is one similar …

Fix static analysis warning

---

ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

expose PredStructure and VideoUsabilityInfo through ffmpeg as pred_struct and vid_info.
Fixes #579

FFmpeg: expose PredStructure and VideoUsabilityInfo

---

ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
ffmpeg_plugin/0002-doc-Add-libsvt_hevc-encoder-docs.patch

In real SVT HEVC use as a part of FFmpeg on multi-socket systems (e.g .Xeon 8260L) there is a strong need to select the target socket to run encoder on to balance the server load evenly. Moreover the ffmpeg plugin should be consistent with GStreamer plugin that has such option.

ffmpeg plugin: target CPU socket option added

---

Source/Lib/Codec/EbEncDecProcess.c
Source/Lib/Codec/EbPictureDecisionProcess.c
Source/Lib/Codec/EbReferenceObject.h
Source/Lib/Codec/EbResourceCoordinationProcess.c
Source/Lib/Codec/EbSystemResourceManager.c

double release leads to duplicated objects in empty queue

fix EB_ENC_PD_ERROR4 EB_ENC_PD_ERROR8 in race conditions

---

ffmpeg_plugin/master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

Replace ff_alloc_packet2 with ff_alloc_packet in the patch of master branch.
And simple verification has been done.
Fixes #598

FFmpeg: replace packet alloc interface in the patch of master branch

---

Source/Lib/Codec/EbInitialRateControlProcess.c

With command line in #602, behavior is different between gcc-10 and 8.
gcc-10 gives `floating point exception` for `divide by zero`. gcc-8 simply returns 0.
This PR fixes the exception when code is compiled with gcc-10.
#602
@tianjunwork

Fix a divide by zero issue

---

ffmpeg_plugin/master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch

ffmpeg file "configure" has been changed.
https://github.com/FFmpeg/FFmpeg/commit/f32f56468c6caa03f4ebbf6cf58b2bb7bc775216
So there is an error when I run `git apply ../SVT-HEVC/ffmpeg_plugin/master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch`:
```
error: patch failed: configure:3315
error: configure: patch does not apply
```
This change fixes this error.
Kusaanko

Fix an issue that ffmpeg patch files could not be applied

---

ffmpeg_plugin/0002-doc-Add-libsvt_hevc-encoder-docs.patch

- #587 added new lines without updating hunk offsets
- #591 bumped minimum ffmpeg version to `n4.4`
- `n4.4` has https://github.com/ffmpeg/ffmpeg/commit/6accb7718aa4

ffmpeg_plugin: rebase documentation against ffmpeg n4.4
