- Source/App/EbAppMain.c
Clean up the samples
- add tips if run samples fail
- add fail check for malloc/free
> Clean up the samples

- Source/Lib/System/EbEncDecProcess.c
> lib/system/EbEncDecProcess: Coding style clean up.

- Source/Lib/Codec/EbCoeffEstimation_Intrinsic.c
- Source/Lib/Codec/EbMdRateEstimation.c
- Source/Lib/Codec/EbProductCodingLoop.c
- Source/Lib/Codec/EbRateDistortionCost.c
- Source/Lib/Codec/EbTransforms.c
- Source/Lib/System/EbPictureAnalysisProcess.c
- Source/Lib/System/EbSourceBasedOperationsProcess.c
Added static for functions used within the same file
> Fix build failure for O0 optimization level

- ffmpeg_plugin/install_libsvt_hevc_ffmpeg.sh
Update svt-hevc FFmpeg plugin install script.
> ffmpeg_plugin: Update install script.

- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
- ffmpeg_plugin/0002-Changelog-Add-new-entry-for-svt-hevc-encoder.patch
- ffmpeg_plugin/README.txt
- ffmpeg_plugin/libsvt_hevc.c
- Update the patch, split a total patch to 2 patch, one is FFmpeg plugin, the other is for Changelog entry.
- Update README.txt based on above change.
> FFmpeg plugin: Update ffmpeg plugin part.

- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
- ffmpeg_plugin/0002-doc-Add-libsvt_hevc-encoder-docs.patch
- ffmpeg_plugin/export_libsvt_hevc.sh
Update SVT-HEVC FFmpeg plugin part.
Note: Now I move the Changelog entry, it's always lead to the merge fail,
but will add it when we try to upstream the plugin to FFmpeg maillist.
> FFmpeg plugin: Fix SVT-HEVC FFmpeg plugin patch fail issue

- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Fix build fail when SVT-HEVC refine the API
Signed-off-by: Jun Zhao <mypopydev@gmail.com>
> FFmpeg Plugin: Fix build fail when SVT-HEVC API change

- Source/Lib/Codec/EbModeDecision.c
add the line:
#define REVERT_LIMITINRA_MPM_PATCH
in EbDefinitions.h to revert the patch
> Add macro to revert the Limit Intra MPM patch

- Source/SimpleApp/EbSimpleAppContext.c
- Source/SimpleApp/EbSimpleAppMain.c
> Fix the crash if command input error

- Source/Lib/Codec/EbCodingLoop.c
- Source/Lib/Codec/EbEncDecProcess.c
> Fix the dump recon mismatch for non-dlf/SAO case

- Source/Lib/Codec/EbEncHandle.c
Signed-off-by: Jing SUN <jing.a.sun@intel.com>
> Fix the frame-rate computation potential overflow issue.

- Source/App/EbAppConfig.c
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbMotionEstimation.c
- Source/Lib/Codec/EbProductCodingLoop.c
- Source/Lib/Codec/EbRateControlProcess.c
- Removed self-assigning code
- Replaced fopen to open
> Fix kw issues

- Source/Lib/Codec/EbEncDecProcess.c
In previous implementation, some recon frame may get lost. The buf with
EOS may not be the last one due to multi-threading
> Fix the multi-thread issue while dumping recon

- README.md
> Switch Travis badge from travis-ci.org to travis-ci.com

- Source/Lib/Codec/EbEntropyCoding.c
> Fix the frame rate issue

- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Signed-off-by: Jing SUN <jing.a.sun@intel.com>
> FFmpeg-Plugin: Add the support to svt hevc and av1 plugins coexistance

- Source/App/EbAppContext.c
- Source/App/EbAppProcessCmd.c
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbPictureControlSet.c
Solving compiling errors with `Intel C++ 19.0 compiler`.
> Fix compiling error with 'Intel C++ 19.0 compiler'.

- Source/Lib/Codec/EbModeDecision.c
#Issue 124
This is a bugfix for #124 . Bugs in entropy coding was fixed.
> Fix YUV420p10 format encoding error.

- Docs/svt-hevc_encoder_user_guide.md
- Source/App/EbAppConfig.c
- Source/App/EbAppContext.c
- Source/Lib/Codec/EbEncHandle.c
> Remove the deprecated latency parameter (#100)

- Docs/svt-hevc_encoder_user_guide.md
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbThreads.h
> Allocate resource based on number of logical processor configed.

- Config/Sample.cfg
Add the missing hashtag/pound on the last section of flags
> Fix missing Pound

- Config/Sample.cfg
- Source/API/EbApi.h
- Source/App/EbAppConfig.c
- Source/App/EbAppConfig.h
- Source/App/EbAppContext.c
- Source/Lib/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Codec/EbCodingLoop.c
- Source/Lib/Codec/EbCodingUnit.h
- Source/Lib/Codec/EbDefinitions.h
- Source/Lib/Codec/EbEncDecProcess.c
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbEntropyCoding.c
- Source/Lib/Codec/EbEntropyCoding.h
- Source/Lib/Codec/EbEntropyCodingProcess.c
- Source/Lib/Codec/EbPictureControlSet.h
- Source/Lib/Codec/EbPictureManagerProcess.c
- Source/Lib/Codec/EbProductCodingLoop.c
- Source/Lib/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Codec/EbSequenceControlSet.h
- Source/SimpleApp/EbSimpleAppContext.h
> #define  TILES    1  //enable TILES.

- gstreamer-plugin/CMakeLists.txt
- gstreamer-plugin/README.md
- gstreamer-plugin/gstsvthevcenc.c
- gstreamer-plugin/gstsvthevcenc.h
- gstreamer-plugin/meson.build
> GStreamer plugin

- gstreamer-plugin/gstsvthevcenc.c
> [gst-plugin]Add config for new SVT-HEVC API

- Config/Sample.cfg
- Docs/svt-hevc_encoder_user_guide.md
- Source/API/EbApi.h
- Source/App/EbAppConfig.c
- Source/App/EbAppConfig.h
- Source/App/EbAppContext.c
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbModeDecision.c
- Source/Lib/Codec/EbPictureDecisionProcess.c
- Source/SimpleApp/EbSimpleAppContext.h
> Add API for config unrestricted motion vector

- Source/App/EbAppContext.c
- Source/Lib/Codec/EbDefinitions.h
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbModeDecision.c
- Source/SimpleApp/EbSimpleAppContext.c
> Increase the output buffer size for 8K streams

- Docs/svt-hevc_encoder_user_guide.md
- Source/App/EbAppConfig.c
- Source/Lib/Codec/EbEncHandle.c
> Update document for new tile API

- Source/Lib/Codec/EbEncHandle.c
> Fix a regression which increases init time

- .gitignore
- Build/windows/build.bat
- Build/windows/generate.bat
- Build/windows/generate_vs17.bat
- README.md
Should I rename the batch file to build.bat to match the linux script?
> Add vs2019. Closes #183

- Source/App/EbAppConfig.c
- Source/Lib/Codec/EbDefinitions.h
- Source/Lib/Codec/EbEncHandle.c
Needs to further check tile setting according to profile/tier/level
> remove tile number limitation

- Source/API/EbApi.h
- Source/App/EbAppConfig.c
- Source/App/EbAppConfig.h
- Source/App/EbAppContext.c
- Source/Lib/Codec/EbBitstreamUnit.h
- Source/Lib/Codec/EbCodingLoop.c
- Source/Lib/Codec/EbCodingUnit.h
- Source/Lib/Codec/EbDefinitions.h
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbEntropyCoding.c
- Source/Lib/Codec/EbEntropyCodingProcess.c
- Source/Lib/Codec/EbModeDecision.c
- Source/Lib/Codec/EbMotionEstimation.c
- Source/Lib/Codec/EbPictureControlSet.h
- Source/Lib/Codec/EbPictureManagerProcess.c
- Source/Lib/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Codec/EbSequenceControlSet.c
- Source/Lib/Codec/EbSequenceControlSet.h
> enable one slie per tile support with restricted MVs

- Source/Lib/Codec/EbModeDecision.c
Original implementation to limit MV at the boundary is not efficient
> Optimize the quality for MCTS

- Source/Lib/Codec/EbModeDecision.c
- Source/Lib/Codec/EbSequenceControlSet.c
> fixed tileEnd error for tileSliceMode

- Source/Lib/Codec/EbBitstreamUnit.h
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbEntropyCoding.c
add level constraint for multi tile and slice case
> add level constraint for multi tile and slice case

- gstreamer-plugin/git-patch/0001-svthevcenc-Add-svthevc-encoder-element.patch
- gstreamer-plugin/git-patch/README.txt
Add SVT-HEVC plugin that runs on latest stable release v1.14.4 of Gstreamer.
> Gstreamer Plugin: Add SVT-HEVC Gstreamer plugin

- gstreamer-plugin/gstsvthevcenc.c
- gstreamer-plugin/gstsvthevcenc.h
- gstreamer-plugin/meson.build
> GST-plugin: Add new features

- README.md
* Adds info about the #svt IRC channel
* Uses correct headings to save space
* Link to the issue tab
> Readme: Add IRC channel, use correct headings

- Source/Lib/Codec/EbEntropyCoding.c
> Fix the finish() in entropycoding

- Source/Lib/Codec/EbEntropyCoding.c
- Source/Lib/Codec/EbSei.c
> Fix writeUvlc long bits bigger than 32 issue and Period SEI error

- Source/Lib/Codec/EbPictureDecisionProcess.c
Pass through frames if SCD not enabled
> Reduce latency for non-scd case

- Build/windows/build.bat
https://github.com/OpenVisualCloud/SVT-HEVC/pull/206#issuecomment-500629793
Addresses issue and add changes from svt-av1 build.bat
> build.bat: fix multifolder, add changes from av1

- Source/Lib/Codec/EbEntropyCoding.c
- Source/Lib/Codec/EbSei.c
Signed-off-by: Kelvin Hu <kelvin.hu@intel.com>
> fixed buffer period sei error

- .travis.yml
Maybe might be better to add a debug build like svt-av1 so that if there are leaks, it would be easier to spot.
Make sure to uncomment out the last line for MacOS once it's confirmed buildable.
> Travis: port changes from SVT-AV1

- Source/Lib/Codec/EbRateControlProcess.c
> Fix the vbr stability issue

- Source/Lib/Codec/EbSampleAdaptiveOffsetGenerationDecision.c
Signed-off-by: Kelvin Hu <kelvin.hu@intel.com>
> fixed SAO eoDiff and eoCount calculating error for YUV422

- CMakeLists.txt
Cherry-pick from SVT-AV1 PR:
https://github.com/OpenVisualCloud/SVT-AV1/pull/431
> Disable native cpu arch

- Source/App/EbAppInputy4m.c
Change PRINT_HEADER usage in EbAppInputy4m.c to satisify Klocwork issue
involving constant 'if' statements.
> Change PRINT_HEADER usage in y4m

- Build/windows/build.bat
- CMakeLists.txt
- README.md
Related issue #234 
Unsure if it completely fixes everything, @111alan, can you test it?
> Batch: Fix Bin folder and other issues

- Source/Lib/Codec/EbEncDecSegments.c
> Add protection in init segments

- Source/Lib/Codec/EbEncHandle.c
Added stride checks when the input frame buffer is being copied
(SDL related issue)
> Stride Checks

- Source/Lib/Codec/EbThreads.c
> Fix the return value of TerminateThread

- Source/Lib/Codec/EbEntropyCoding.c
> Fix the deltaQP issue for intra4x4 with YUV444

- Source/Lib/Codec/EbProductCodingLoop.c
> Fix the avx/C mismatch issue

- Source/Lib/Codec/EbEncDecProcess.c
> Fix bug #235, caused by some legacy code

- Source/App/EbAppInputy4m.c
- Source/App/EbAppProcessCmd.c
Several changes to resolve compile warnings on  Linux.
Also changed validateAlphanumeric for y4m testing to better handle y4m header processing
> Y4m nalu compile issues

- Source/Lib/Codec/EbDefinitions.h
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbMotionEstimation.c
- Source/Lib/Codec/EbMotionEstimationProcess.c
> Clean up warnings and add more info to stdout

- Source/Lib/Codec/EbModeDecision.c
> mcts bug fix for fractional MVs in tile boundary 

- Tests/SVT-HEVC_FunctionalTests.py
> Fix extra M11 test cases in test script

- .travis.yml
> [travis]Stop applying ffmpeg doc only patch

- Source/App/EbAppInputy4m.c
Undefined PRINT_HEADER to prevent the display of y4m header values
> PRINT_HEADER Preprocessor

- Source/Lib/Codec/EbModeDecisionProcess.c
> disable P422 and P444 chroma search for known quality issue

- Source/Lib/Codec/EbEntropyCoding.c
> fixed bug for mcts slice_mode 1

- Source/Lib/ASM_SSE2/EbSaoStatistics_Intrinsic_SSE2.c
When gathering SAO statistics for each LCU, the invalid samples
beyond the right edge of LCU shouldn't be counted, although the
use SSE2 intrinsics can only support __m128i data type. So fixed
the issue for SAO BO counting, as the invalid samples are always
0 and would be counted into BO index 0 containing sample value 0~7.
As for EO, all of the C_DEFAULT implementations
(such as GatherSaoStatisticsLcuLossy_62x62) will shifts edge index
2 and 3, with 3 and 4 separately. And the SSE2 implementation
(countEdge) doesn't handle edge index. So the encoded outputs
wouldn't have bit diff, although the EO diffs and counts of edge
index 4 have some gap, between ASM enabled and disabled.
> [ASM_SSE2] fixed the output mismatching issue with ASM enabled and disabled (Issue #281).

- Source/Lib/Codec/EbEncDecProcess.c
- Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Codec/EbPictureDecisionProcess.c
##Description:
Updated MD / ADP / PF Settings to match those of the old M12 tune0
Signed-off-by: htmar <hassene.tmar@intel.com>
> Faster M11 8k 4k preset

- README.md
> Add CentOS in README

- .travis.yml
- Build/linux/build.sh
- CMakeLists.txt
- README.md
- Source/API/EbTime.h
- Source/App/EbAppContext.c
- Source/App/EbAppMain.c
- Source/App/EbAppProcessCmd.c
- Source/App/EbTime.c
- Source/Lib/Codec/CMakeLists.txt
- Source/Lib/Codec/EbDefinitions.h
- Source/Lib/Codec/EbEncHandle.c
- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
> Support both dynamic/static builds

- Config/Sample.cfg
Changed setting in Sample.cfg to 1 which
matches the default setting in the code
(EbAppConfig.c)
> UnrestrictedMotionVector

- Source/App/EbAppInputy4m.c
- Source/Lib/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Codec/EbCodingLoop.c
- Source/Lib/Codec/EbCodingUnit.h
- Source/Lib/Codec/EbDeblockingFilter.c
- Source/Lib/Codec/EbEncDecProcess.c
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbEntropyCoding.c
- Source/Lib/Codec/EbEntropyCodingProcess.c
- Source/Lib/Codec/EbInitialRateControlProcess.c
- Source/Lib/Codec/EbIntraPrediction.c
- Source/Lib/Codec/EbModeDecision.c
- Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Codec/EbModeDecisionProcess.c
- Source/Lib/Codec/EbMotionEstimation.c
- Source/Lib/Codec/EbMotionEstimationProcess.c
- Source/Lib/Codec/EbPacketizationProcess.c
- Source/Lib/Codec/EbPictureAnalysisProcess.c
- Source/Lib/Codec/EbPictureControlSet.c
- Source/Lib/Codec/EbPictureControlSet.h
- Source/Lib/Codec/EbPictureManagerProcess.c
- Source/Lib/Codec/EbProductCodingLoop.c
- Source/Lib/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Codec/EbSequenceControlSet.c
- Source/Lib/Codec/EbSequenceControlSet.h
- Source/Lib/Codec/EbSourceBasedOperationsProcess.c
- Source/Lib/Codec/EbUtility.h
> Refine and clean up tile related codes

- Source/Lib/Codec/EbModeDecision.c
> fixed mcts check error for AMVP, Bi and Uni pred.

- Source/Lib/Codec/EbEncDecProcess.c
- Source/Lib/Codec/EbInitialRateControlProcess.c
- Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Codec/EbMotionEstimationProcess.c
- Source/Lib/Codec/EbPacketizationProcess.c
- Source/Lib/Codec/EbPictureAnalysisProcess.c
- Source/Lib/Codec/EbPictureAnalysisProcess.h
- Source/Lib/Codec/EbPictureDecisionProcess.c
- Source/Lib/Codec/EbRateControlProcess.c
- Source/Lib/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Codec/EbSourceBasedOperationsProcess.c
> Clean up, add static to local functions

- Source/Lib/Codec/EbEncDecProcess.c
> Only copy/pad refDenSrc if useRefSrc is enabled

- Source/Lib/Codec/EbModeDecision.c
> AMVP: injected the MV candidates with the correct ref list for AMVP.

- Source/Lib/Codec/EbModeDecisionProcess.c
- Source/Lib/Codec/EbPacketizationProcess.c
- Source/Lib/Codec/EbPacketizationReorderQueue.h
- Source/Lib/Codec/EbProductCodingLoop.c
> Add more statistics info

- Source/Lib/Codec/EbModeDecision.c
> Fix mv out of bounds issue for non-mcts encoding

- Config/Sample.cfg
- Docs/svt-hevc_encoder_user_guide.md
- Source/API/EbApi.h
- Source/App/EbAppConfig.c
- Source/App/EbAppConfig.h
- Source/App/EbAppContext.c
- Source/Lib/Codec/EbEncHandle.c
- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
@hassount @lijing0010 @kelvinhu325 @tianjunwork Please kindly review this.
> Add the "-thread-count" parameter support

- Source/Lib/Codec/EbSourceBasedOperationsProcess.c
> skip AC energy(contour) for low latency use

- Source/Lib/Codec/EbModeDecision.c
> fix umv0 out of bounds issue for high motion cases

- Source/Lib/Codec/EbEncDecSegments.c
> Add protection for segments

- CMakeLists.txt
The encoder still displays Encoder Lib v1.4.0
> Update SVT_HEVC_VERSION_PATCHLEVEL to 1 for 1.4.1 release

- CMakeLists.txt
Updated Patchlevel in CMakeLists.txt so that
version shows as: 1.4.1
> Updated patch level

- Tests/README.md
- Tests/SVT-HEVC_FunctionalTests.py
Added new test cases for MCTS, VBV, HDR, and Color
Format.
Modified the mcts test to adjust the maximum column
and row for the tile layout to be based on the frame
size (the number of luma pixels determines max rows and
max cols).
Also moved the actual determination of the max
column and row to where the video has already been
selected for the test.
Added -tile_slice-mode and -umv parameters for the
test.
Added decoding test for mcts to verify resulting bitstream
can be read.  This is similar to existing decode tests.
MCTS tests need to be run using updated HM decoder which
has a positive return code for when the decoding values.
> New Test Cases

- .travis.yml
- Updates Linux build environment to Ubuntu Bionic 18.04
- Updates macOS build environment to macOS 10.14 with Xcode 11.0
- Update FFmpeg to 4.2 branch
> Travis maintenance: Update build environments, FFmpeg

- Docs/svt-hevc_encoder_user_guide.md
+ Added doc changes for BufferedInput
+ Made several other minor changes (spelling, format)
> User Guide changes

- Source/App/EbAppConfig.c
- Source/App/EbAppConfig.h
- Source/App/EbAppMain.c
Having "--help" and "--version" is to be consistent with other linux based programs.
- "--help" same as "-help" prints help message.
- "--version" same as "-v" prints version information.
> Add --version to sample app

- Source/App/EbAppConfig.c
- Source/App/EbAppMain.c
> Block CompressedTenBitFormat ON for non-420 color format

- Tests/README.md
- Tests/SVT-HEVC_FunctionalTests.py
Updating the test script provided by Jing.
Updated the README.md to reflect the updated script.
> Updated test script

- Source/Lib/Codec/EbEncHandle.c
> Addressed the SIGFPE issue with VBV settings and CQP rate control mode.

- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
> FFmpeg-Plugin: add vbv maxrate and bufsize

- Docs/svt-hevc_encoder_user_guide.md
- Source/API/EbApi.h
- Source/Lib/Codec/EbEncHandle.c
> Matched the default configuration parameters between README and encoder.

- Source/App/EbAppConfig.c
- Source/Lib/Codec/EbCodingLoop.c
1) Removed configuration check that disallowed YUV444 10 bit compressed
configuration
2) Change the LCU stride for the YUV444 incremental buffer  chroma from
32 to 64
> YUV444 10bit compressed

- Source/Lib/Codec/EbEncHandle.c
> Fix wrong core number print

- Source/App/EbAppInputy4m.c
- Source/App/EbAppProcessCmd.c
> Fix reading input for fifo in ReadInputFrames

- CMakeLists.txt
> Updated version to 1.4.2

- Source/Lib/Codec/EbEncHandle.c
Missed one since I didn't test on windows yet
> GetAffinityMask: Prefix with EbHevc

- Source/App/EbAppProcessCmd.c
> Fix macOS build

- appveyor.yml
> Appveyor: Merge Unix+FFmpeg Job and clean up artifacts

- Source/Lib/Codec/CMakeLists.txt
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbEncHandle.h
- Source/Lib/Codec/EbPictureOperators.c
- Source/Lib/Codec/EbPictureOperators.h
- Source/Lib/Codec/EbSequenceControlSet.h
- Source/Lib/Codec/EbUnPackProcess.c
- Source/Lib/Codec/EbUnPackProcess.h
Multithreading the Unpack2D function to remove bottleneck for non compressed 10 bits files in resolutions greater than 4k.
> Multithreading of Unpack2D

- Source/Lib/Codec/EbEncDecSegments.c
- Source/Lib/Codec/EbEncHandle.c
By fixing some typos, and addressing an out of memory boundary issue.
Fixes #459 .
> Fixed the encoding crash issue when width < height.

- Source/Lib/Codec/EbDefinitions.h
- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbEntropyCoding.c
- Source/Lib/Codec/EbEntropyCoding.h
- Source/Lib/Codec/EbInitialRateControlProcess.c
- Source/Lib/Codec/EbPacketizationProcess.c
Signed-off-by: Austin Hu austin.hu@intel.com
Fixes #64 , #458
> Fixed output buffer too small issue

- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Also need to review and merge it once PR #457 is merged.
> ffmpeg plugin: reported error code from invalid packet.

- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
> ffmpeg plugin: add para umv

- Source/Lib/Codec/EbEncHandle.c
> Clean up useless function

- appveyor.yml
Fixes issue in appveyor with packages not being installed because of gcc
> appveyor: update pacman packages along with installing them

- Source/Lib/Codec/EbDefinitions.h
> Disable OUT_ALLOC which causes hang for several cases

- Source/Lib/Codec/EbEncHandle.c
- Source/Lib/Codec/EbEntropyCoding.c
Adding some casting to remove compile warnings
> Compile warnings

- appveyor.yml
Will try to port release artifact uploading to github actions later
> Appveyor: Disable artifact uploading for now

- Source/Lib/Codec/EbPacketizationProcess.c
> Fix typo in PK

- Docs/svt-hevc_encoder_user_guide.md
> Add more details of header insertion in user guide

- Config/SVTSegmentOvFile.txt
- Docs/svt-hevc_encoder_user_guide.md
Add more explanation for -segment-ov parameter
#545 
@tszumski
> Add more explanation for -segment-ov parameter

- Source/App/EbAppMain.c
- Source/App/EbAppProcessCmd.c
- Source/Lib/Codec/EbEncHandle.c
Fix issues reported by klocwork.
@tianjunwork
> Fix klocwork warning

- ffmpeg_plugin/README.md
> Update README in ffmpeg plugin

- ffmpeg_plugin/README.md
Fix ffmpeg readme
@tianjunwork
> Update README for ffmpeg plugin

- CMakeLists.txt
Update version to 1.5.0
Functional test known issues are recorded in Github. #371.
@tianjunwork
> Update version to 1.5.0

- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Move some of the lines to allow patching the master branch, 4.3, and 4.2 with the same file
tested with ffmpeg tags n4.2*, n4.3*, and n4.4-dev
tested with ffmpeg branch [master](https://github.com/FFmpeg/FFmpeg/commit/1c7e55dd504245d71444fac1a73e5370cc76fede), release/4.2, and release/4.3 
@guojiansheng0925 can you please review?
@1480c1
> ffmpeg: Move lines to allow applying on master, 4.3, and 4.2

- Config/Sample.cfg
- Source/API/EbApi.h
Removed a reference to the Tune parameter in the sample configuration
file (Sample.cfg)
> Remove Tune reference in cfg

- ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
update FFmpeg plugin patch
closes #576 
@guojiansheng0925
> FFmpeg: update plugin patch for master branch

- CMakeLists.txt
- appveyor.yml
Fix appveyor failure
@tianjunwork
> Fix appveyor failure

- Source/Lib/Codec/EbString.c
Updated Safe String Library license text
in EbString.c
> Updated license text

- ffmpeg_plugin/master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
rebase master branch patch
fixes #614
> FFmpeg: Rebase master branch

- ffmpeg_plugin/master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
> FFmpeg: Rebase on master branch

- ffmpeg_plugin/master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
rebases the master patch
@1480c1
> ffmpeg_patch: rebase master patch
